
---
- name: Basic Troubleshooting BGP
  hosts: ceos1
  gather_facts: false
  vars:
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4

  tasks:

    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: BGP Details
      debug:
       var: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
        commands: "{{ switches }}"
      register: result

    - name: print
      debug:
       msg: "{{ result }}"
