---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Update switch ceos1 from webhook
      condition: event.payload.text is search("ceos2")
      action:
       run_playbook:
         name: update_ceos2.yml

    - name: Connect Eth 1 on all switches
      condition: event.payload.text is match("update-my-switch") 
      action: 
       run_playbook:
         name: update_from_src.yml

    - name: Webhook Event from Mattermost
      condition: event.payload.text is match("maintenance ceo2")
      action:
        run_playbook:
          name: set_maintenance.yml
