---
- name: Connecting to Leaf
  hosts: "{{ ansible_eda.event.name }}"
  connection: local
  gather_facts: false
  vars:
   ansible_connection: ansible.netcommon.network_cli
   ansible_network_os: arista.eos.eos
   ansible_user: ansible
   ansible_password: ansible
   ansible_become: yes
   ansible_become_method: enable


  tasks:

#    - name: debug
#      debug:
#        msg: "{{ ansible_eda.event.name }}"

    - name: Correct Interfaces
      arista.eos.eos_interfaces:
        config:
         - name: Ethernet1
           enabled: true
